version: '3.7'

services:
  whois-server:
    container_name: whois-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3030:3030